using System;
using System.Collections.Generic;

namespace UtilityNGPKG.PaymentGateway.Paystack.DTOs
{
    /// <summary>
    /// Represents the payload sent to initialize a Paystack payment.
    /// </summary>
    public class PaymentInitRequest
    {
        /// <summary>
        /// The unique ID of the user making the payment.
        /// </summary>
        public Guid UserId { get; set; }

        /// <summary>
        /// The full name of the customer making the payment.
        /// </summary>
        public string CustomerName { get; set; }

        /// <summary>
        /// The amount to be paid. Must be in major currency (e.g., Naira, not Kobo). The system will automatically convert it to Kobo.
        /// </summary>
        public decimal Amount { get; set; }

        /// <summary>
        /// The customer's email address.
        /// </summary>
        public string Email { get; set; }

        /// <summary>
        /// The currency for the transaction. Defaults to NGN.
        /// </summary>
        public string Currency { get; set; } = "NGN";

        /// <summary>
        /// The callback URL Paystack will redirect the user to after the payment process.
        /// </summary>
        public string CallbackUrl { get; set; }

        /// <summary>
        /// Additional metadata or custom fields you want to pass along with the transaction to Paystack.
        /// </summary>
        public Dictionary<string, object> Metadata { get; set; } = new();

        /// <summary>
        /// The unique identifier for the transaction generated by the system.
        /// </summary>
        public Guid TransactionId { get; set; }

        /// <summary>
        /// The unique transaction reference. If not provided, one will be generated.
        /// </summary>
        public string Reference { get; set; }

        /// <summary>
        /// Allows you to specify the payment channels to be available to the user. E.g. ["card", "bank"].
        /// </summary>
        public List<string> Channels { get; set; }
    }
}
