namespace UtilityNGPKG.PaymentGateway.Paystack.DTOs
{
    /// <summary>
    /// Contains details required to authorize a payment transaction on Paystack.
    /// </summary>
    public class PaymentData
    {
        /// <summary>
        /// The URL the user should be redirected to in order to complete the payment.
        /// </summary>
        public string AuthorizationUrl { get; set; }

        /// <summary>
        /// The access code generated by Paystack for the transaction.
        /// </summary>
        public string AccessCode { get; set; }

        /// <summary>
        /// The unique reference associated with the transaction.
        /// </summary>
        public string Reference { get; set; }
    }
}
