using System;
using System.Security.Cryptography;
using System.Text;

namespace UtilityNGPKG.PaymentGateway.Paystack.DTOs
{
    /// <summary>
    /// Utility class meant for verifying incoming Paystack webhook requests using HMAC SHA512 signature hash validation.
    /// </summary>
    public class PaystackWebhookVerifier
    {
        /// <summary>
        /// Validates that an incoming request genuinely originated from Paystack using their hashing convention and your secret key.
        /// </summary>
        /// <param name="body">The raw serialized JSON payload string coming from Paystack webhook.</param>
        /// <param name="signatureHeader">The signature generated by Paystack typically received in the 'x-paystack-signature' header.</param>
        /// <param name="secret">Your Paystack Secret key, which Paystack uses to sign the webhook event.</param>
        /// <returns>True if the hash is valid; Otherwise, false indicating the request shouldn't be verified as authentic.</returns>
        public static bool IsValidPaystackSignature(string body, string signatureHeader, string secret)
        {
            using var hmac = new HMACSHA512(Encoding.UTF8.GetBytes(secret));
            var hash = hmac.ComputeHash(Encoding.UTF8.GetBytes(body));
            string hashString = BitConverter.ToString(hash).Replace("-", "").ToLower();

            return hashString == signatureHeader.ToString().ToLower();
        }
    }
}
