namespace UtilityNGPKG.PaymentGateway.Paystack.DTOs
{
    /// <summary>
    /// Represents the details of a transfer recipient created on Paystack.
    /// </summary>
    public class RecipientData
    {
        /// <summary>
        /// The unique recipient code generated by Paystack, to be used for initiating transfers.
        /// </summary>
        public string RecipientCode { get; set; }

        /// <summary>
        /// The type of recipient (typically 'nuban').
        /// </summary>
        public string Type { get; set; }

        /// <summary>
        /// The validated name of the account holder.
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// The 10-digit NUBAN account number.
        /// </summary>
        public string AccountNumber { get; set; }

        /// <summary>
        /// The Paystack bank code of the recipient's bank.
        /// </summary>
        public string BankCode { get; set; }
    }
}
